language: node_js
addons:
  firefox: 'latest'
node_js:
  - '8.9'

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - $CI_ACTION

env:
  global:
    - TEST_SUITE=unit
  matrix:
    - CI_ACTION="npm run test:ci"
    - CI_ACTION="npm run dist"
    # - CI_ACTION="npm run lint"

branches:
  only:
    - master

cache:
  directories:
    - node_modules
